config/routes.rb
RecipeBoxSecond::Application.routes.draw do
  devise_for :users
  get "welcome/index"
  resources :users
  resources :recipes

  root 'welcome#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

	validates :name, presence: true, length: {minimum: 2}

	mount_uploader :picture, PictureUploader

	belongs_to :user


	def minutes_total
		if (minutes_to_prepare)
			minutes_to_prepare + minutes_to_cook
		else
			minutes_to_cook
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :category, :instructions, :minutes_to_prepare, :minutes_to_cook, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper



#full disclosure: I had to google this code (found on Stack Overflow)

#Lesson: googling is a coder's best friend; don't

#think you need to know the answer to every problem

#right off the top of your head.



def resource_name

:user

end



def resource

@resource ||= User.new

end



def devise_mapping

@devise_mapping ||= Devise.mappings[:user]

end



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sean's Recipes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- Bootstrap links: -->

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">



	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
<!-- Devise notice/alert -->

<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :minutes_to_prepare %><br>
    <%= f.number_field :minutes_to_prepare %>
  </div>
  <div class="field">
    <%= f.label :minutes_to_cook %><br>
    <%= f.number_field :minutes_to_cook %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1 class="green">Tech Talent Recipe Book</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Category</th>
      <th>Instructions</th>
      <th>Minutes to Make</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe %></td>
        <td><%= image_tag (recipe.picture_url), :width =>200 %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.instructions %></td>
        <td><%= recipe.minutes_total %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Picture</strong>
  <%= image_tag(@recipe.picture_url, :width => 600) if @recipe.picture.present? %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<p>
  <strong>Minutes to prepare:</strong>
  <%= @recipe.minutes_to_prepare %>
</p>

<p>
  <strong>Minutes to cook:</strong>
  <%= @recipe.minutes_to_cook %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/welcome/_signin.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>

	<p><strong>Email:</strong> <%= f.text_field :email %></p>

	<p><strong>Password:</strong> <%= f.password_field :password %></p>

	<p><%= f.check_box :remember_me %> <%= f.label :remember_me %></p>

	<p><%= f.submit 'Sign In' %></p>

	<p><%= link_to "Forgot your password?", new_password_path(:user) %></p>

<% end %>

app/views/welcome/_signup.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

	<%= devise_error_messages! %>



	<p><%= f.label :email %><br />

	<%= f.email_field :email, autofocus: true %></p>



	<p><%= f.label :name %><br />

	<%= f.text_field :name %></p>


	<p><%= f.label :password %><br />

	<%= f.password_field :password, autocomplete: "off" %></p>



	<p><%= f.label :password_confirmation %><br />

	<%= f.password_field :password_confirmation, autocomplete: "off" %></p>



	<div><%= f.submit "Sign up" %></div>

<% end %>

app/views/welcome/index.html.erb
<div class="page-header"><h1>Tech Talent Recipes <small>A Totally Original Idea</small></h1></div>



<% if user_signed_in? %>

	<% if current_user.recipes.empty? %>
			<p>No recipes here...</p>
			<p>Start cookin'!</p>

	<% else %>
			<table>
				<thead>
				   <tr>
				    <th>Name</th>
				    <th>Picture</th>
				    <th>Category</th>
				    <th>Instructions</th>
				    <th>Minutes to Make</th>
				    <th></th>
				    <th></th>
				    <th></th>
				   </tr>
				</thead>

				<tbody>
				   <% current_user.recipes.each do |recipe| %>
				    	<tr>
				        <td><%= link_to recipe.name, recipe %></td>
				        <td><%= image_tag (recipe.picture_url), :width =>200 %></td>
				        <td><%= recipe.category %></td>
				        <td><%= recipe.instructions %></td>
				        <td><%= recipe.minutes_total %></td>
				        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
				        <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				      </tr>
				    <% end %>
				  </tbody>
				</table>

		<% end %>
		<%= link_to 'New Recipe', new_recipe_path %></br>
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>

<% else %>

	<div class="container">

		<div class="col-md-6">

			<h3>Welcome Back! Sign In:</h3><br />


		<%= render 'signin' %>

		</div>


		<div class="col-md-6">

			<h3>Not yet registered?</h3><br />

			<%= render 'signup' %>

		</div>

	</div>

<% end %>